# dimensions
const MAX_WIDTH = 500
const MAX_HEIGHT = 500

# polygons
const POLYGONS_MIN = 50
const POLYGONS_MAX = 255

# points
const POINTS_PER_POLYGON_MIN = 3
const POINTS_PER_POLYGON_MAX = 10
const POINTS_MIN = POINTS_PER_POLYGON_MIN*POLYGONS_MIN
const POINTS_MAX = 1500


# mutation rates
const ADD_POLYGON_MUTATION_RATE = 700
const REMOVE_POLYGON_MUTATION_RATE = 1500
const MOVE_POLYGON_MUTATION_RATE = 700
const ADD_POINT_MUTATION_RATE = 1500
const REMOVE_POINT_MUTATION_RATE = 1500
const MOVE_POINT_MAX_MUTATION_RATE = 1500
const MOVE_POINT_MID_MUTATION_RATE = 1500
const MOVE_POINT_MIN_MUTATION_RATE = 1500
const RED_MUTATION_RATE = 1500
const GREEN_MUTATION_RATE = 1500
const BLUE_MUTATION_RATE = 1500
const ALPHA_MUTATION_RATE = 1500

# ranges
const MOVE_POINT_RANGE_MID = 20
const MOVE_POINT_RANGE_MIN = 3
const RED_RANGE_MAX = 255
const RED_RANGE_MIN = 0
const GREEN_RANGE_MAX = 255
const GREEN_RANGE_MIN = 0
const BLUE_RANGE_MAX = 255
const BLUE_RANGE_MIN = 0
const ALPHA_RANGE_MAX = 60
const ALPHA_RANGE_MIN = 30

